DeadLock: DeadLock Class Reference
DeadLock Class Reference
#include <deadlock.h>
Public Member Functions
void init (string projectName)
Initializes the environment and creates project.
void notebookGenerate (string projectName)
Generate the Python notebook.
void pyFileGenerate (string projectName)
Generate the Python File.
void gitignoreGenerate (string projectName)
Generate the .gitignore.
void readmeGenerate (string projectName)
Generate the README.md.
void userOption ()
bool isPythonAvailable ()
Checks if Python is installed and accessible in the system's PATH.
string apiCaller (string url)
Perform an HTTP Get request to the given URL Using cURL.
bool downloadPackage (string packageName, string version)
Downloads a platform-compatible Python package wheel from PyPI.
bool installPackage (string package)
bool installPackages (vector< string > packages)
Package getPackageInfo (string packageName)
Retrieves package metadata from the PyPI JSON API.
string getLatestVersion (string packageName)
Retrieves the latest version of a package from PyPI.
bool extractWheelToVenv (string wheelPath, string venvPath)
Extracts a wheel file to the specified virtual environment.
bool createVirtualEnvironment (string venvPath)
Creates a virtual environment at the specified path.
bool generateDeadLockFile (string projectPath=gProjectName)
bool updateDeadLockFile (Package pkg)
bool removeFromDeadLockFile (string packageName)
bool isPackageInstalled (string packageName)
bool syncFromDeadLock (string projectPath=gProjectName)
string getDeadLockFilePath ()
Returns path of dead.lock file.
string getCurrentTimestamp ()
vector< string > getPackageDependencies (string packageName)
Gets necessary required packages of the provided package.
vector< Package > getInstalledPackages ()
string readDeadLockFile (string filePath)
Public Attributes
vector< string > installedPackages
Static Public Attributes
static string gProjectName = "."
Detailed Description
Definition at line 11 of file deadlock.h.
Member Function Documentation
apiCaller()
string DeadLock::apiCaller (string url)
Perform an HTTP Get request to the given URL Using cURL.
This function initializes a cURL session sends the request, collect the response and return the server's reply as the string.
Parameters
url The target URL to which the HTTP GET request will be send.
Returns
std::string The response body from the server, or an empty string if the request fails.
Definition at line 101 of file deadlock.cpp.
References WriteCallback().
Referenced by downloadPackage(), getLatestVersion(), getPackageDependencies(), and getPackageInfo().
createVirtualEnvironment()
bool DeadLock::createVirtualEnvironment (string venvPath)
Creates a virtual environment at the specified path.
This function checks if a virtual environment already exists at the given path, and if not, it creates a new virtual environment using Python's venv module.
Parameters
venvPath The path where the virtual environment should be created.
Returns
bool True if the virtual environment was successfully created or already exists, false otherwise.
Definition at line 639 of file deadlock.cpp.
Referenced by init(), and syncFromDeadLock().
downloadPackage()
bool DeadLock::downloadPackage (string packageName, string version)
Downloads a platform-compatible Python package wheel from PyPI.
This function retrieves package metadata from the PyPI JSON API for the given package name and version, determines the appropriate wheel file for the current operating system (Windows, macOS, or Linux), and downloads it to the local "downloads" directory. If the version is not provided, the latest available version is fetched automatically.
Parameters
packageName The name of the Python package to download.
version The version of the package to download. If empty, the latest version is used.
Returns
bool True if the package is successfully downloaded, false otherwise.
Definition at line 329 of file deadlock.cpp.
References apiCaller(), basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), getLatestVersion(), and WriteToFile().
extractWheelToVenv()
bool DeadLock::extractWheelToVenv (string wheelPath, string venvPath)
Extracts a wheel file to the specified virtual environment.
This function renames the wheel file to a zip file, extracts its contents to a temporary directory, and then copies the extracted files to the site-packages directory of the virtual environment.
Parameters
wheelPath The path to the wheel file to be extracted.
venvPath The path to the virtual environment where the package will be installed.
Returns
bool True if the extraction and installation were successful, false otherwise.
Definition at line 796 of file deadlock.cpp.
generateDeadLockFile()
bool DeadLock::generateDeadLockFile (string projectPath = gProjectName)
Definition at line 1028 of file deadlock.cpp.
References basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::dump(), getCurrentTimestamp(), and getDeadLockFilePath().
Referenced by installPackage(), and updateDeadLockFile().
getCurrentTimestamp()
string DeadLock::getCurrentTimestamp ()
Definition at line 1181 of file deadlock.cpp.
Referenced by generateDeadLockFile(), and installPackage().
getDeadLockFilePath()
string DeadLock::getDeadLockFilePath ()
Returns path of dead.lock file.
Returns
std:string The path of dead.lock file
Definition at line 1177 of file deadlock.cpp.
Referenced by generateDeadLockFile(), installPackage(), isPackageInstalled(), removeFromDeadLockFile(), syncFromDeadLock(), and updateDeadLockFile().
getInstalledPackages()
vector< Package > DeadLock::getInstalledPackages ()
Definition at line 1308 of file deadlock.cpp.
Referenced by main().
getLatestVersion()
string DeadLock::getLatestVersion (string packageName)
Retrieves the latest version of a package from PyPI.
This function queries the PyPI JSON API for the specified package and extracts the latest version from the response.
Parameters
packageName The name of the package to query on PyPI.
Returns
string The latest version of the package, or an empty string if not found.
Definition at line 601 of file deadlock.cpp.
References apiCaller(), basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), and detail::exception::what().
Referenced by downloadPackage(), getPackageInfo(), and installPackages().
getPackageDependencies()
vector< string > DeadLock::getPackageDependencies (string packageName)
Gets necessary required packages of the provided package.
This function queries PYPI and retrieves info about all the required dependencies of the provided package.
Parameters
packageName The name of the package whose dependencies are required.
Returns
An array containing names of required deoendencies.
Definition at line 1202 of file deadlock.cpp.
References apiCaller(), basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), and detail::exception::what().
Referenced by getPackageInfo(), and installPackages().
getPackageInfo()
Package DeadLock::getPackageInfo (string packageName)
Retrieves package metadata from the PyPI JSON API.
This function sends an HTTP GET request to the PyPI JSON API for the specified package, parses the response to extract key package information including name, latest version, source designation, and dependencies.
Parameters
packageName The name of the package to query on PyPI.
Returns
Package An object containing package details such as name, version, source, and dependencies.
Definition at line 572 of file deadlock.cpp.
References apiCaller(), Package::dependencies, getLatestVersion(), getPackageDependencies(), Package::name, Package::source, and Package::version.
Referenced by installPackage(), and main().
gitignoreGenerate()
void DeadLock::gitignoreGenerate (string projectName)
Generate the .gitignore.
Parameters
projectName The name of the project.
Definition at line 238 of file deadlock.cpp.
Referenced by init().
init()
void DeadLock::init (string projectName)
Initializes the environment and creates project.
This function gets invoked when create argument is passed in CLI.
Parameters
projectName The name of the project, the name specified here should not change in the future.
Definition at line 139 of file deadlock.cpp.
References createVirtualEnvironment(), gitignoreGenerate(), gProjectName, isPythonAvailable(), notebookGenerate(), pyFileGenerate(), readmeGenerate(), and userOption().
Referenced by main().
installPackage()
bool DeadLock::installPackage (string package)
Definition at line 459 of file deadlock.cpp.
References basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), Package::empty(), generateDeadLockFile(), getCurrentTimestamp(), getDeadLockFilePath(), getPackageInfo(), Package::installDate, isPackageInstalled(), readDeadLockFile(), updateDeadLockFile(), and detail::exception::what().
Referenced by installPackages().
installPackages()
bool DeadLock::installPackages (vector< string > packages)
Definition at line 494 of file deadlock.cpp.
References getLatestVersion(), getPackageDependencies(), installedPackages, and installPackage().
Referenced by main(), syncFromDeadLock(), and userOption().
isPackageInstalled()
bool DeadLock::isPackageInstalled (string packageName)
Definition at line 1115 of file deadlock.cpp.
References basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), getDeadLockFilePath(), readDeadLockFile(), and detail::exception::what().
Referenced by installPackage().
isPythonAvailable()
bool DeadLock::isPythonAvailable ()
Checks if Python is installed and accessible in the system's PATH.
Returns
bool True if Python is available in the PATH, false otherwise.
Definition at line 307 of file deadlock.cpp.
Referenced by init(), and main().
notebookGenerate()
void DeadLock::notebookGenerate (string projectName)
Generate the Python notebook.
Parameters
projectName The name of the project.
Definition at line 171 of file deadlock.cpp.
References basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::dump(), and basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::object().
Referenced by init().
pyFileGenerate()
void DeadLock::pyFileGenerate (string projectName)
Generate the Python File.
Parameters
projectName The name of the project.
Definition at line 219 of file deadlock.cpp.
Referenced by init().
readDeadLockFile()
string DeadLock::readDeadLockFile (string filePath)
Definition at line 1298 of file deadlock.cpp.
Referenced by installPackage(), isPackageInstalled(), and updateDeadLockFile().
readmeGenerate()
void DeadLock::readmeGenerate (string projectName)
Generate the README.md.
Parameters
projectName The name of the project.
Definition at line 289 of file deadlock.cpp.
Referenced by init().
removeFromDeadLockFile()
bool DeadLock::removeFromDeadLockFile (string packageName)
Definition at line 1088 of file deadlock.cpp.
References getDeadLockFilePath().
syncFromDeadLock()
bool DeadLock::syncFromDeadLock (string projectPath = gProjectName)
Definition at line 1143 of file deadlock.cpp.
References createVirtualEnvironment(), getDeadLockFilePath(), and installPackages().
Referenced by main().
updateDeadLockFile()
bool DeadLock::updateDeadLockFile (Package pkg)
Definition at line 1052 of file deadlock.cpp.
References basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::contains(), Package::dependencies, basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::dump(), generateDeadLockFile(), getDeadLockFilePath(), Package::installDate, Package::name, basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::push_back(), readDeadLockFile(), Package::source, Package::version, and detail::exception::what().
Referenced by installPackage().
userOption()
void DeadLock::userOption ()
Definition at line 1312 of file deadlock.cpp.
References gProjectName, and installPackages().
Referenced by init().
Member Data Documentation
gProjectName
string DeadLock::gProjectName = "." static
Definition at line 14 of file deadlock.h.
Referenced by init(), and userOption().
installedPackages
vector<string> DeadLock::installedPackages
Definition at line 16 of file deadlock.h.
Referenced by installPackages().
The documentation for this class was generated from the following files:
deadlock.h
deadlock.cpp