name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deadlock-executable
        path: build/DeadLock
